version: "3.9"
services:
  ddns-job:
    image: go-r53-ddns:v0.2.0
    environment:
      - HOSTED_ZONE_ID=Z00284422N70TQP6B6C1
      - CLUSTER_DOMAIN=cluster.scribbd.cloud.
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
    command: "/app/ddns"