apiVersion: {{ .Values.cronConf.apiVersion }}
kind: CronJob
metadata:
  name: {{ include "go-r53-ddns.name" . }}-cronjob
  labels:
    {{- include "go-r53-ddns.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronConf.schedule }}
  jobTemplate:
    metadata:
      name: 
        labels: {{ include "go-r53-ddns.name" . }}-jobTemplate
      labels:
        {{- include "go-r53-ddns.labels" . | nindent 8 }}
    spec:
      template:
        metadata:
          name: {{ include "go-r53-ddns.name" . }}-job
          labels:
            {{- include "go-r53-ddns.labels" . | nindent 12 }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:

              resources:
                {{- toYaml .Values.resources | nindent 16 }}

              env:
                {{- include "go-r53-ddns.envGen" .Values.cronConf.env | indent 16 -}}
                {{- include "go-r53-ddns.envFromSecretGen" . | indent 16 -}}

          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}