apiVersion: {{ .Values.cronConf.apiVersion }}
kind: CronJob
metadata:
  name: {{ include "go-r53-ddns.fullname" . }}-cronjob
  labels:
    {{- include "go-r53-ddns.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronConf.schedule }}
  jobTemplate:
    metadata:
      name: 
        labels: {{ include "go-r53-ddns.fullname" . }}-jobTemplate
      labels:
        {{- include "go-r53-ddns.labels" . | nindent 8 }}
    spec:
      template:
        metadata:
          name: {{ include "go-r53-ddns.fullname" . }}-job
          labels:
            {{- include "go-r53-ddns.labels" . | nindent 12 }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:

              resources:
                {{- toYaml .Values.resources | nindent 16 }}

              env:
              {{- range $key,$value := .Values.envFromSecrets }}
                - name: {{ $value.key | upper | quote}}
                  valueFrom:
                    secretKeyRef:
                      name: {{ $value.from.secret | quote}}
                      key: {{ $value.from.key | quote}}
              {{- end }}
              {{- range $key,$value := .Values.env }}
                - name: {{ $key | upper | quote}}
                  value: {{ required "All environment values have to be set." $value | quote}}
              {{- end }}

          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}