{{ if .Values.secretConf.deploy }}
apiVersion: {{ .Values.secretConf.apiVersion }}
kind: Secret
metadata:
  {{- $defaultName := printf "%s-%s" (include "go-r53-ddns.name" . ) ("secret") }}
  name: {{ default .Values.secretConf.name $defaultName }}
  labels:
    {{- include "go-r53-ddns.labels" . | nindent 4 }}
type: "Opaque"
data:
{{- range $_,$value := .Values.secretConf.secrets }}
  {{ $value.key }}: {{ (required (cat "Secret value is required for" $value.key) $value.value) | b64enc | quote }}
{{- end }}

{{ end }}