{{ if .Values.secretConf.generate }}
apiVersion: {{ .Values.secretConf.apiVersion }}
kind: Secret
metadata:
{{ if .Values.secretConf.name }}
  name: {{ .Values.secretConf.name }}
{{ else }}
  name: {{ include "go-r53-ddns.fullname" . }}-secret
{{ end }}
  labels:
    {{- include "go-r53-ddns.labels" . | nindent 4 }}
type: "Opaque"
data:
{{- range $key,$value := .Values.secretConf.secrets }}
  {{ $value.key }}: {{ $value.value | b64enc | quote }}
{{- end }}

{{ end }}