---
name: Tag Push = Publish Release

on:
  push:
    branches: 
      - $default-branch
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            README.md
            LICENSE

  build-container:
    runs-on: ubuntu-latest
    env:
      DOCKER_NAMESPACE: scribbd
      DOCKER_REPO: go-r53-ddns
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPO }}
            ghcr.io/${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-executable:
    needs: create-release
    runs-on: ubuntu-latest
    env:
      GO_VERSION: v1.17
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm, arm64]
        include:
          - goos: windows
            goarch: amd64
    steps:
    - uses: actions/checkout@v2

    - uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.RELEASE_SECRET }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: env.GO_VERSION
        project_path: ./golang/
        release-tag: "${{ env.GITHUB_REF_NAME }}"

  package-helm:
    needs: build-container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: ./helm/
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"